server:
  port: 8094
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: content-store-service

  # kafka
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

  # Elasticsearch
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}
    username: ${ELASTIC_USERNAME:root}
    password:  ${ELASTIC_PASSWORD:root}

  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      embedding:
        options:
          model: ${OLLAMA_EMBEDDING_MODEL:hf.co/nomic-ai/nomic-embed-text-v2-moe-GGUF:Q6_K}
      init:
        pull-model-strategy: when_missing
        chat:
          include: false

elasticsearch:
  host: ${ELASTICSEARCH_HOST:localhost}
  port: ${ELASTICSEARCH_PORT:9200}


management:
  health:
    elasticsearch:
      enabled: false
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      service: ${spring.application.name}
      instance: ${server.port}


# Logging Configuration
logging:
  level:
    com.vdt.crawler.content_store_service: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
    org.springframework.data.mongodb: INFO
    org.elasticsearch: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/content-store-service.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30

springdoc:
  swagger-ui:
    path: /api/docs